name: mri_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - mock=3.0
  - nibabel=2.5.*
  - nilearn=0.6.*
  - babel=2.5.*
  - h5py=2.7
  - hdf5=1.10
  - joblib=0.13.2
  - jupyter=1.0.0
  - matplotlib=2.1.*
  - nbconvert=5.3
  - notebook=5.4
  - numpy=1.16.*
  - pandas=0.22
  - pytest=5.4.*
  - seaborn=0.9.*
  - scikit-learn=0.22
  - scipy=1.3.*
  - seaborn=0.8.*
  - torchvision=0.4.*
  - wheel=0.33
  - xlsxwriter=1.0.2
  - xlrd=1.2.0
  - yaml=0.1.7